# This file was generated by GoReleaser. DO NOT EDIT.
cask "onebox" do
  version "2026.9.0"

  on_macos do
    on_arm do
      sha256 "3d8cd03f0d48d8f70164856ad77f5edba85ac5346971abc7d149f5950248c39e"
      url "https://github.com/labstack/onebox/releases/download/v#{version}/onebox_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/labstack/onebox/"
    end
    on_intel do
      sha256 "7950aa3de513c675f7e2132c4d1d2fb645ea9fb85c44d3e0a3b9fa3e3d431638"
      url "https://github.com/labstack/onebox/releases/download/v#{version}/onebox_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/labstack/onebox/"
    end
  end
  on_linux do
    on_arm do
      sha256 "b9949355eb6b79a62707e8797881bfd3bd1ce3e8a6d02aaa786ba0f29029ad7c"
      url "https://github.com/labstack/onebox/releases/download/v#{version}/onebox_#{version}_linux_arm64.tar.gz",
        verified: "github.com/labstack/onebox/"
    end
    on_intel do
      sha256 "7fb081d8578a59b234a98de43de337ec0816f91e71e81e2c6d72f7eea2964695"
      url "https://github.com/labstack/onebox/releases/download/v#{version}/onebox_#{version}_linux_amd64.tar.gz",
        verified: "github.com/labstack/onebox/"
    end
  end

  name "onebox"
  desc "Production operations for an application intentionally running on one server."
  homepage "https://onebox.run"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ob"

  # No zap stanza required
end
