# This file was generated by GoReleaser. DO NOT EDIT.
cask "onebox" do
  version "2026.8.4"

  on_macos do
    on_intel do
      sha256 "eb02506e873e691118d60a7cf5ab6e32fb7d3f0aeaa8f51f4773f8dea39cf775"
      url "https://github.com/labstack/onebox/releases/download/v#{version}/onebox_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/labstack/onebox/"
    end
    on_arm do
      sha256 "e25e3d72a4c00976cdc300ed5c1d27024a6c5aa36bb0f33fbb826016f0249636"
      url "https://github.com/labstack/onebox/releases/download/v#{version}/onebox_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/labstack/onebox/"
    end
  end

  on_linux do
    on_intel do
      sha256 "a0a985513b8c9897707f984275521955a0852cd33fd0fcbee578ece7a5f24ebc"
      url "https://github.com/labstack/onebox/releases/download/v#{version}/onebox_#{version}_linux_amd64.tar.gz",
        verified: "github.com/labstack/onebox/"
    end
    on_arm do
      sha256 "c3dbae1f40fb58d7078f75bed760a529b247d0b2403de310924f8e4617b1158d"
      url "https://github.com/labstack/onebox/releases/download/v#{version}/onebox_#{version}_linux_arm64.tar.gz",
        verified: "github.com/labstack/onebox/"
    end
  end

  name "onebox"
  desc "Production operations for an application intentionally running on one server."
  homepage "https://onebox.run"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ob"

  # No zap stanza required

end
