# This file was generated by GoReleaser. DO NOT EDIT.
cask "onebox" do
  version "2026.9.10"

  on_macos do
    on_arm do
      sha256 "83abac8bc6f362a964b24c705729d782029722459d7efb52047edc5e009e6c9e"
      url "https://github.com/labstack/onebox/releases/download/v#{version}/onebox_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/labstack/onebox/"
    end
    on_intel do
      sha256 "215bc4ee64d133789f188534b9790b13eb0066dbea96007d425bc6f355a5eb39"
      url "https://github.com/labstack/onebox/releases/download/v#{version}/onebox_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/labstack/onebox/"
    end
  end
  on_linux do
    on_arm do
      sha256 "5893e65f282966ea834583f8de75054c12ff0edf6b41216433475574ba66116d"
      url "https://github.com/labstack/onebox/releases/download/v#{version}/onebox_#{version}_linux_arm64.tar.gz",
        verified: "github.com/labstack/onebox/"
    end
    on_intel do
      sha256 "0678d112f8d19c36e54b26948a9b19044021c51d58855e520e5b78bf75ea1393"
      url "https://github.com/labstack/onebox/releases/download/v#{version}/onebox_#{version}_linux_amd64.tar.gz",
        verified: "github.com/labstack/onebox/"
    end
  end

  name "onebox"
  desc "Production operations for an application intentionally running on one server."
  homepage "https://onebox.run"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ob"

  # No zap stanza required
end
